### ISSUE TITLE
Request to transfer ownership of the crate

### ISSUE THREAD

**Issue by h3nill** [rep-nop/mosiac#1]
Hello, from the [mosaic](https://github.com/mosaic-org/) team. We are building a [terminal workspace](https://github.com/mosaic-org/mosaic) that has the same name as a crate you own. We are a completely open-source team of enthusiasts from around the world, and would very much like to be able to use the `mosaic` name.

From what we can see, your repository with the same name is not being maintained anymore and all the versions published on crates.io have been yanked.

So if you don't plan to further maintain the repository, we were wondering if you would be willing to transfer the name to us on crates.io?

I've also emailed you based on the email submitted in the commits of this repo.

We thank you in advance.

Kind regards,
The Mosaic Team.

**Comment by repnop** [comment]
Hi! Unfortunately I no longer have access to the crate, I had a request to transfer it around August of last year, but it doesn't look like that person has actually published anything using the name. You'll want to get into contact with https://crates.io/users/tmandry and ask them if they still have plans to use the name on crates.io. Good luck!

**Comment by h3nill** [comment]
Thank you for replying. We will try contacting them. Have a Good day :smile:
